### ISSUE TITLE
数据库存储路径是哪里呢？

### ISSUE THREAD

**Issue by LiuYinCarl** [songquanpeng/go-file#1]

**Comment by songquanpeng** [comment]
工作目录，名称为 .go-file.db，注意开头是 "." 依次在类 UNIX 系统中是隐藏文件。
详见：https://github.com/songquanpeng/go-file/blob/1c326afd5281b2e173321e9f118b821dbf6c7edf/model.go#L25

**Comment by LiuYinCarl** [comment]
在代码里找到了 `./go-file.db` 是数据库路径。我觉得需要在界面上添加一个清空数据库/s删除数据库的按钮。这样用起来会比较方便。

**Comment by LiuYinCarl** [comment]
回复有够快的 ^_^

**Comment by songquanpeng** [comment]
嗯，可以考虑，已加入开发计划，预计周末开始搞：
https://github.com/songquanpeng/go-file/projects/1#card-56183414

有邮件提醒 :D

**Comment by LiuYinCarl** [comment]
刚才的一个使用场景是：我要在局域网内分享一个 600G 的文件夹，但是是在公司，所以不能用移动硬盘。但是这个软件当前好像不支持以文件夹为单位分享。遍历文件夹导致一直卡在命令行。所以我直接杀掉了进程。等到我重启 go-file 的时候，网页里面出现了一个很大的文件列表，所以我觉得，这个软件在这种场景下的支持可能还不够全面。

**Comment by songquanpeng** [comment]
> 不支持以文件夹为单位分享

没办法直接分享整个文件夹，除非打包成单个文件

> 遍历文件夹导致一直卡在命令行

里面是不是有很多文件？遍历时会把所有子文件夹（除了 . 开头的）都遍历一遍。
将来可以开个单独的协程来遍历，这样就不会卡了，已加入开发计划：
https://github.com/songquanpeng/go-file/projects/1#card-56183977

> 出现了一个很大的文件列表

我还没来及做分页。

感谢反馈！

**Comment by LiuYinCarl** [comment]
还有一个问题是文件分享的功能是需要将上传的文件缓存到某个目录吗？我刚好看了下代码没有找到。另外一个问题如果我在分享的过程中删除了文件，但是文件信息已经存储到了数据库，等下其他设备下载的话会找不到文件，数据库会自动删除这个不存在的文件吗？好像没有看到这个处理。

**Comment by songquanpeng** [comment]
> 还有一个问题是文件分享的功能是需要将上传的文件缓存到某个目录吗？
是的，因为考虑到别的用户也能上传。你可在命令行加参数上传某个文件夹中的内容，这样是不会缓存的。

> 数据库会自动删除这个不存在的文件吗？
如果是在本地删除的文件（没有通过系统），下载的话会 404，数据库目前还不会将其删除，我忘记做处理了，感谢反馈，已加入开发计划。

**Comment by LiuYinCarl** [comment]
如果程序在服务端提供一个接口返回一个包含目录结构的json/xml，我可以尝试实现写一个客户端，通过读取这个json/xml 来分批次拉取目录下的所有文件，在客户端重新构建目录接口，实现目录的分享。

**Comment by songquanpeng** [comment]
提供 API 的话应该没什么困难，预计本周末去搞，https://github.com/songquanpeng/go-file/projects/1#card-56185844

**Comment by songquanpeng** [comment]
不好意思啊，最近比较忙，这个就暂且放下了

**Comment by LiuYinCarl** [comment]
没关系,我自己在尝试写一个工具来是实现了。
