### ISSUE TITLE
关于配置保存方式的疑问 & SSL？

### ISSUE THREAD

**Issue by SkyYkb** [songquanpeng/go-file#10]
## 关于配置保存方式的疑问

请问这个程序通过什么来保存配置内容呢？鉴于不需要配置环境，是自动生成SQLite数据库还是保存成配置文件了？
（我真的不怎么会看源码😂）

## SSL？

作者有没有打算支持SSL？我知道我可以套Nginx，但是如果支持了好像更省事诶。

**Comment by songquanpeng** [comment]
1. SQLite，名称为 .go-file.db，所以在 unix 系统下是隐藏的。
2. 感觉一般都是套 Nginx。
