### ISSUE TITLE
不支持arm吗？

### ISSUE THREAD

**Issue by sharljimhtsin** [songquanpeng/go-file#11]
root@cubieboard:~/share# ./go-file
2022/07/13 13:08:58 Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

启用cgo编译报错，

[root@VM-4-3-centos go-file]# CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -o arm32_cgo
# runtime/cgo
gcc: error: unrecognized command line option '-marm'
[root@VM-4-3-centos go-file]# CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o arm64_cgo
# runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:28: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:32: Error: too many memory references for `mov'
gcc_arm64.S:34: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:37: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:40: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:43: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:46: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:50: Error: too many memory references for `mov'
gcc_arm64.S:51: Error: too many memory references for `mov'
gcc_arm64.S:52: Error: too many memory references for `mov'
gcc_arm64.S:54: Error: no such instruction: `blr x20'
gcc_arm64.S:55: Error: no such instruction: `blr x19'
gcc_arm64.S:57: Error: no such instruction: `ldp x27,x28,[sp,'
gcc_arm64.S:60: Error: no such instruction: `ldp x25,x26,[sp,'
gcc_arm64.S:63: Error: no such instruction: `ldp x23,x24,[sp,'
gcc_arm64.S:66: Error: no such instruction: `ldp x21,x22,[sp,'
gcc_arm64.S:69: Error: no such instruction: `ldp x19,x20,[sp,'
gcc_arm64.S:72: Error: no such instruction: `ldp x29,x30,[sp],'
[root@VM-4-3-centos go-file]#

**Comment by songquanpeng** [comment]
在 Arm 版 macOS 上是可以编译成功的，Linux 版本还没试过。
https://github.com/songquanpeng/go-file/issues/9#issuecomment-1181498453

**Comment by songquanpeng** [comment]
你是在非 Arm PC 上编译 Arm 版本吗？我感觉如果是这样的话是环境配置的问题。

看下这个：https://github.com/golang/go/issues/28966#issuecomment-547558462

**Comment by sharljimhtsin** [comment]
> 你是在非 Arm PC 上编译 Arm 版本吗？我感觉如果是这样的话是环境配置的问题。
> 
> 看下这个：https://github.com/golang/go/issues/28966#issuecomment-547558462

我在amd64的centos上编译的，出现了上面的错误。我试试你发的文章里的办法

**Comment by sharljimhtsin** [comment]
编译出来了，用了这个docker镜像

https://hub.docker.com/r/neilotoole/xcgo

安装arm和arm64的交叉编译环境

root@e247c0249aab:~/go-file# apt install gcc-8-aarch64-linux-gnu
root@e247c0249aab:~/go-file# CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc-8 CGO_LDFLAGS="-static" go build -o arm64_cgo

root@cubieboard:~/share# file arm64_cgo
arm64_cgo: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.7.0, Go BuildID=AalnnEQekidqmptZquGz/aSoMd6TA73QBkm0IDqG_/SUbpHXoJ18WFRgSG6rzU/VfL9KOTxjNpxqDEtfy0K, BuildID[sha1]=1deaa9fe1c2975134e70eb738968bc28f54030b9, not stripped

root@e247c0249aab:~/go-file# apt install gcc-8-arm-linux-gnueabihf
root@e247c0249aab:~/go-file# CGO_ENABLED=1 GOOS=linux GOARCH=arm CC=arm-linux-gnueabihf-gcc-8 CGO_LDFLAGS="-static" go build -o arm32_cgo

root@cubieboard:~/share# file arm32_cgo
arm32_cgo: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, Go BuildID=8Wg1yb4ZZzlG4sdXJHrT/fU9BAJLIDqQo4IjcKFZl/kpsAYVoH16QcZCdKkMwG/il82YXu2geC_M_s1KAzI, BuildID[sha1]=7a5d684faebe60165ecc7010dd6d0af74d7268c9, not stripped

**Comment by songquanpeng** [comment]
我感觉是不是可以在这里（https://github.com/songquanpeng/go-file/blob/74d237a25b438c43f94be29baa02d77e2d99229b/.github/workflows/linux-release.yml#L1）直接一次性打包好 ARM 版本和 x86 版本？

**Comment by sharljimhtsin** [comment]
> 我感觉是不是可以在[这里](https://github.com/songquanpeng/go-file/blob/74d237a25b438c43f94be29baa02d77e2d99229b/.github/workflows/linux-release.yml#L1)直接一次性打包好 ARM 版本和 x86 版本？

那是最好的，有全平台的预编译binary 极大的方便用户。github action 就是干这个的，配置一次，一直可以生成发布

**Comment by sharljimhtsin** [comment]
在arm 32bit系统有bug，


```

2022/07/18 13:42:15 [Recovery] 2022/07/18 - 13:42:15 panic recovered:
runtime error: integer divide by zero
/usr/lib/go-1.17/src/runtime/panic.go:200 (0x77b47)
/usr/lib/go-1.17/src/runtime/vlrt.go:143 (0x77b08)
/root/go-file/common/utils.go:64 (0x51f923)
/root/go-file/controller/page-explorer.go:72 (0x596673)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x59af2f)
/root/go-file/middleware/check.go:21 (0x59abe4)
/root/go-file/middleware/check.go:57 (0x59d98f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x59c353)
/root/go-file/middleware/rate-limit.go:84 (0x59c300)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x59c0d7)
/root/go-file/middleware/rate-limit.go:53 (0x59c084)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x592773)
/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 (0x592750)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a3443)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 (0x4a3420)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a26e7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 (0x4a26c4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a1bdb)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x4a18e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x4a14d3)
/usr/lib/go-1.17/src/net/http/server.go:2878 (0x27519b)
/usr/lib/go-1.17/src/net/http/server.go:1929 (0x270f5f)
/usr/lib/go-1.17/src/runtime/asm_arm.s:838 (0x7e1eb)

[GIN] 2022/07/18 - 13:42:15 | 500 |    9.481352ms |   43.254.222.66 | GET      "/explorer"

```

```

2022/07/18 13:42:29 [Recovery] 2022/07/18 - 13:42:29 panic recovered:
runtime error: integer divide by zero
/usr/lib/go-1.17/src/runtime/panic.go:200 (0x77b47)
/usr/lib/go-1.17/src/runtime/vlrt.go:143 (0x77b08)
/root/go-file/common/utils.go:64 (0x51f923)
/root/go-file/controller/page-video.go:78 (0x59785b)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x59c0d7)
/root/go-file/middleware/rate-limit.go:53 (0x59c084)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x592773)
/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 (0x592750)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a3443)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/recovery.go:99 (0x4a3420)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a26e7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/logger.go:241 (0x4a26c4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x4a1bdb)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x4a18e0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x4a14d3)
/usr/lib/go-1.17/src/net/http/server.go:2878 (0x27519b)
/usr/lib/go-1.17/src/net/http/server.go:1929 (0x270f5f)
/usr/lib/go-1.17/src/runtime/asm_arm.s:838 (0x7e1eb)

[GIN] 2022/07/18 - 13:42:29 | 500 |    8.665756ms |   43.254.222.66 | GET      "/video"

```

系统信息：


```

root@cubieboard:~/share# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 619.95
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : Allwinner sun4i/sun5i Families
Revision        : 0000
Serial          : 1623674e05c2de21
root@cubieboard:~/share# uname -a
Linux cubieboard 5.15.43-sunxi #22.05.1 SMP Sat May 28 08:17:47 UTC 2022 armv7l GNU/Linux
root@cubieboard:~/share# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@cubieboard:~/share#

```

**Comment by sharljimhtsin** [comment]
是不是 int64 这玩意不兼容？我在我另外一块arm 64位的板子上没复现这个bug.

**Comment by songquanpeng** [comment]
感觉是溢出了？我手头没 32 位的板子没法测试，把这个 sizeTB 这里直接去掉可以编译成功吗？
https://github.com/songquanpeng/go-file/blob/1ecdb458029c0b4270b761f181440db604f8396c/common/utils.go#L65

**Comment by sharljimhtsin** [comment]
删除TB这个变量，问题消失。


```

root@cubieboard:~/share# ./arm32_cgo -no-browser -path ../pkg/
[GIN] 2022/07/18 - 14:47:28 | 200 |   26.396109ms |   43.254.222.66 | GET      "/explorer"
[GIN] 2022/07/18 - 14:47:28 | 200 |  167.596629ms |   43.254.222.66 | GET      "/public/lib/qrious.min.js"
[GIN] 2022/07/18 - 14:47:28 | 200 |  160.694107ms |   43.254.222.66 | GET      "/public/static/app.css"
[GIN] 2022/07/18 - 14:47:28 | 200 |   47.254468ms |   43.254.222.66 | GET      "/public/static/main.js"
[GIN] 2022/07/18 - 14:47:28 | 200 |  217.324217ms |   43.254.222.66 | GET      "/public/lib/bulma.min.css"
[GIN] 2022/07/18 - 14:47:28 | 200 |    1.311144ms |   43.254.222.66 | GET      "/public/static/favicon.png"

```

修改：


```

diff --git a/common/utils.go b/common/utils.go
index c5b8c1a..51c68c0 100644
--- a/common/utils.go
+++ b/common/utils.go
@@ -57,15 +57,11 @@ func GetIp() (ip string) {
 var sizeKB = 1024
 var sizeMB = sizeKB * 1024
 var sizeGB = sizeMB * 1024
-var sizeTB = sizeGB * 1024

 func Bytes2Size(num int64) string {
        numStr := ""
        unit := "B"
-       if num/int64(sizeTB) > 1 {
-               numStr = fmt.Sprintf("%f", float64(num)/float64(sizeTB))
-               unit = "TB"
-       } else if num/int64(sizeGB) > 1 {
+       if num/int64(sizeGB) > 1 {
                numStr = fmt.Sprintf("%f", float64(num)/float64(sizeGB))
                unit = "GB"
        } else if num/int64(sizeMB) > 1 {

```
