### ISSUE TITLE
优化视频播放页面

### ISSUE THREAD

**Issue by stong12345** [songquanpeng/go-file#13]
大神，看了你这个系统，非常好，我一直在找一个可以用于互联网的简单的视频，pdf文件分享工具，建议系统增加一下功能：
1、前端和管理端分开设计
2、支持视频介绍，浏览视频前有一个对视频的介绍
3、支持PDF等文件浏览
谢谢

**Comment by songquanpeng** [comment]
1. 目前的管理端是有什么问题么？
2. 是指可以设置视频的描述信息吗？
3. 是指 PDF 文件页面内直接浏览吗？

**Comment by stong12345** [comment]
现在管理端和视频分享的页面在一个页面上，我的想法是这样的：
1、可以在互联网上使用，需要把上传权限严格限制，只有管理员才有，把分享页面和管理页面分开，不在一个页面上
2、需求就是支持视频分享和文本信息分享，包括pdf文件分享
3、浏览视频的时候旁边有一个对视频的文字介绍
4、支持视频、文字分类




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/go-file"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [songquanpeng/go-file] 建议 (Issue #13)





  
目前的管理端是有什么问题么？
 
是指可以设置视频的描述信息吗？
 
是指 PDF 文件页面内直接浏览吗？

**Comment by songquanpeng** [comment]
1. 管理页面是可以设置文件上传下载权限的。
2. 了解。
3. 了解。
4. 加 tag 么？了解。

**Comment by stong12345** [comment]
我下载用了，详细看了你设计的这个系统，非常不错，只要改动部分就可以用于互联网了，希望大佬能够实现以下功能，谢谢！
1、管理页面可以设置权限，这个功能已经有，只是管理页面和前端页面分开比较好，不在一个网页上，像一般的网站那样分开设计
2、浏览视频的时候可以加文字介绍，这个功能已经有；还需要支持文字信息包括pdf文件分享功能
3、还有就是账号管理需要加强下，账号管理用列表的形式给出管理
4、在前端页面支持视频、文字类信息以列表形式分类展示，如下面：&nbsp;&nbsp;








也才可以做成一般网站那样菜单形式那样的

**Comment by songquanpeng** [comment]
管理页面之后是有打算升级的，之后打算用 React 重写，谢谢建议。

第四点是有图吗？这里看不到。

**Comment by stong12345** [comment]
我在网络上找了好久都没有找到想到想要的系统，分享视频和文本信息，应该有很多人都和我有同样的需求，我自己会c/s程序设计，不会b/s的，感觉Go写的程序用起来好简单，一个文件搞定，后面你的系统更新了我第一时间使用，第四点就是一张图片，像这样的一个列表形式的菜单：


C++ 语言
第一章 C++ 语言入门
第二章 顺序结构程序设计
&nbsp; 第一节 运算符和表达式
&nbsp; 第二节 常量和变量
&nbsp; 第三节 标准数据类型
&nbsp; 第四节 数据输入输出
&nbsp; 第五节 顺序结构实例
第三章 程序的控制结构
&nbsp; 第一节 if选择结构
&nbsp; 第二节 switch语句
第四章 循环结构的程序设计
&nbsp; 第一节 for语句
&nbsp; 第二节 while语句
&nbsp; 第三节 do-while语句
&nbsp; 第四节 循环嵌套
第五章 数组
&nbsp; 第一节 一维数组
&nbsp; 第二节 二维数组
&nbsp; 第三节 字符类型和字符数组
第六章 函数
&nbsp; 第一节 函数
&nbsp; 第二节 递归算法





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songquanpeng/go-file"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [songquanpeng/go-file] 建议 (Issue #13)





 
管理页面之后是有打算升级的，之后打算用 React 重写，谢谢建议。
 
第四点是有图吗？这里看不到。

**Comment by songquanpeng** [comment]
感觉是类似 B 站的那种播放列表？然后是支持多个层级，每一项对应一个视频，点击每一项播放对应的视频？

**Comment by stong12345** [comment]
CRMEB知识付费系统
MeEdu-开源知识付费系统


像上面两个开源系统的简化版就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 中午11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [songquanpeng/go-file] 建议 (Issue #13)




 
感觉是类似 B 站的那种播放列表？然后是支持多个层级，每一项对应一个视频，点击每一项播放对应的视频？

**Comment by songquanpeng** [comment]
视频播放页面已更新，目前不考虑做太复杂了。
