### ISSUE TITLE
搜索不到

### ISSUE THREAD

**Issue by bewareilive** [songquanpeng/go-file#14]
版本v0.4.2
只有页签在首页时上传的才能搜到，在其他（比如文件）时，搜索不到

**Comment by songquanpeng** [comment]
是这样的，是因为只有在首页上传的才入了数据库。

**Comment by songquanpeng** [comment]
非首页上传的文件也不会出现在首页，首页和其他页面是独立的，只是共用了一个上传按钮，之后readme会更新来减少误解

**Comment by bewareilive** [comment]
> 是这样的，是因为只有在首页上传的才入了数据库。

1.是功能难实现，还是故意这么区分呢？都入数据库可以搜索不好吗？
2.另外再求教个问题：我现在是在d盘A目录运行的，A目录下生成了upload文件夹，我在里面还手动创建了几个文件夹。
  现在有E:/文档 目录。我希望能在显示upload文件夹的同时，也显示一个“文档”文件夹，现有的能实现吗？
3. 删除的输入URL不太好使用，能不能在列表把数据ID显示，用ID删呢？删除应该也是只能删首页传的吧

**Comment by songquanpeng** [comment]
1. 故意这样区分的，
+ 首页：用户上传文件进行分享，入库，文件上传到 upload 文件夹内
+ 文件：站长指定分享本地的文件夹进行分享（如果站长在启动时不指定要分享的目录，则默认为 upload 文件夹），不入库，文件上传到当前文件夹内
2. `./go-file.exe --path E:/文档`
3. 删除文件：
+ 首页：登录后直接点击删除按钮
+ 文件：因为这个是用来分享已有的文件，所以暂时无法在网页端删除文件
+ 图床：在管理页面使用 url 删除（图床功能后续将得到改进，当前只是满足了最低要求）

**Comment by bewareilive** [comment]
> 1. 故意这样区分的，
> 
> * 首页：用户上传文件进行分享，入库，文件上传到 upload 文件夹内
> * 文件：站长指定分享本地的文件夹进行分享（如果站长在启动时不指定要分享的目录，则默认为 upload 文件夹），不入库（之前有版本是入库的，但是这样的话如果下次启动你的分享文件夹有变动，数据库还要更新，比较麻烦，至于文件的搜索，这个后续会考虑每次启动时建立一个临时表来解决），文件上传到当前文件夹内
> 
> 2. `./go-file.exe --path E:/文档`，目前仅能指定一个目录进行分享，如果这个需求比较多的话，后续可以考虑支持分享多个目录，目前是建议手动把要分享的目录集中在一个文件夹内，或者开多个，如果是 Linux 系统可以建立软连接
> 3. 删除文件：
> 
> * 首页：登录后直接点击删除按钮
> * 文件：因为这个是用来分享已有的文件，所以暂时无法在网页端删除文件（但是我 API 已经写好了，只是前端还没加上操作按钮）
> * 图床：在管理页面使用 url 删除（图床功能后续将得到改进，当前只是满足了最低要求）

感谢回复。
其他问题其实还好，就是第一点，目录分享无法搜索，这个都还能理解。
和其他人交流后，他们是有”为什么上传的文件，有时能搜到，有时搜不到“这种疑惑。

在看了您的解释后，我有些理解设计思维了：
首页是一个单独的模式，支持入库，功能全。其他基本仅是文件发布，即使上传也是类似添加一个静态发布。

那么这里其实可以把首页改个名称，比如资源库（当然也不恰当），事实上他也不是个首页的作用；
然后把搜索栏和上传按钮，单独放到这个这个页签页面顶部，其他则只放个”添加“按钮（就是现在的上传）。
这样就能让人理解，搜索栏只对”资源库“这个页面生效。

当然，这样的话，页面是没现在简洁美观的，这只是一个思路。

目前我的解决办法是在“修改底部信息”里，用大号字，写了文字说明只在首页页签下上传才能搜索。
如果可以，更愿意隐藏了其他页签时的“上传”按钮。
因为如果是让大家都上传分享，那首页的功能就能满足，还能搜索；
如果是想分享文件夹给别人，那一般也不想让他们对这个文件夹下的文件做改变。

**Comment by songquanpeng** [comment]
感谢反馈，
> 目前我的解决办法是在“修改底部信息”里，用大号字，写了文字说明只在首页页签下上传才能搜索。

后续版本可以加入公告功能，其实现在也可以在文件页面下上传 README.md 文件也可以作为公告使用（不过没有置顶）。

> 更愿意隐藏了其他页签时的“上传”按钮

这个上传按钮的多义性的问题确实需要解决，将来在调用出的上传对话框里补充更多的提示信息。
