### ISSUE TITLE
为首页上传的文件创建次级目录

### ISSUE THREAD

**Issue by bewareilive** [songquanpeng/go-file#16]
1.现在首页上传的文件，直接update或者分享的文件夹根目录下，导致根目录很混乱。
能不能给放到一个次级目录，如update/default。
2.添加个复制链接按钮吧，方便分享给别人，现在都是点开下载复制的
ps：试了下系统管理的修改底部信息，发现就是插入一段HTML代码，那是不是可以把首页弄成可以自定义的HTML或markdown页面呢。
我现在是把 那个gotext 用ifream弄到底部了🤣

**Comment by songquanpeng** [comment]
1. 或许可以按照上传时间来组织？
2. Okay，这个好搞，下个版本加上。
3. 首页自定义 HTML 这个主意不错，我之前也在想怎么增加可玩性。

谢谢建议。

**Comment by bewareilive** [comment]
> 1. 或许可以按照上传时间来组织？其实可以手动指定的，设置环境变量就好了，比如 `UPLOAD_PATH =upload/default`。
> 2. Okay，这个好搞，下个版本加上。
> 3. 首页自定义 HTML 这个主意不错，我之前也在想怎么增加可玩性。
> 
> 谢谢建议。

复制链接建议使用url转码前的， 这样链接回比较短，简洁清爽，也能从URL中的中文名直接知道分享的是什么。
还有就是权限控制能到目录，有些目录只是只读分享的，并不希望谁把文件给上传进去。

**Comment by songquanpeng** [comment]
1. Okay
2. 建议不错。

**Comment by bewareilive** [comment]
请教个问题，因为不是关于这个软件的建议，就不重新开帖了：
我看了下你这几个小软件都是基于go的，
想实现一个配置好linux服务器shell脚本，然后发布一个web服务，页面就几个按钮，点击按钮执行相应的脚本。
这种用go好实现不，会不会有系统权限问题。
工作中经常需要些服务器操作，但是前端开发等人又不熟悉，很需要这样一个简易操作的页面。

**Comment by bewareilive** [comment]
> 1. Okay
> 2. 建议不错。

请教个问题，因为不是关于这个软件的建议，就不重新开帖了：
我看了下你这几个小软件都是基于go的，
想实现一个配置好linux服务器shell脚本，然后发布一个web服务，页面就几个按钮，点击按钮执行相应的脚本。
这种用go好实现不，会不会有系统权限问题。
工作中经常需要些服务器操作，但是前端开发等人又不熟悉，很需要这样一个简易操作的页面。

**Comment by songquanpeng** [comment]
好搞，实际上就类似于 Webhook Server 那种，应该已经有现成的了。

系统权限问题的话，你执行脚本前确保其已经有执行权限就好了。

我之前搞了一个类似的，但是没有 Web 界面，https://github.com/songquanpeng/webhook

**Comment by bewareilive** [comment]
> 好搞，实际上就类似于 Webhook Server 那种，应该已经有现成的了。
> 
> 系统权限问题的话，你执行脚本前确保其已经有执行权限就好了。
> 
> 我之前搞了一个类似的，但是没有 Web 界面，https://github.com/songquanpeng/webhook

这个明显比go系列就麻烦了，我不是go开发，看不大懂🤣。不过看说明，其中一个环节的确是实现类似功能了。
按需求以web+shell搜索，就搜到一大堆的web操作终端。
目前就是找些可以参考的，然后以上手较简单的直接使用，或者自己照着做个。
