### ISSUE TITLE
linux无法启用访问数据统计

### ISSUE THREAD

**Issue by pishen12138** [songquanpeng/go-file#18]
系统是centos7.9，宝塔面板安装并启用redis，但设置访问数据统计时，提示：未启用 Redis，无法启用统计功能
请问要设置什么吗？
能否像设置MySQL一样设置环境变量或者通过端口访问redis

**Comment by songquanpeng** [comment]
`REDIS_CONN_STRING` 环境变量，比如：`redis://default:redispw@localhost:49153`
