### ISSUE TITLE
希望添加支持文字分享的功能和扫码打开首页

### ISSUE THREAD

**Issue by tensor-tech** [songquanpeng/go-file#20]
两个建议
1. 直接分享文字，不用新建文件

2. 最好 启动器能生成一个 二维码，扫码就能打开首页

**Comment by songquanpeng** [comment]
收到，谢谢建议，最近在重构，所以可能不会很快实现，已加入 TODO

**Comment by songquanpeng** [comment]
已支持直接创建文本文件，该功能在下个版本发布。
