### ISSUE TITLE
建议文本访问增加UI，可以适配移动端快速复制文本内容

### ISSUE THREAD

**Issue by yuyongID** [songquanpeng/go-file#21]
场景：电脑访问首页，自动创建了文本，手机扫描二维码方位该文本。
现象：手机直接打开了该文件，由于没有UI，所以未适配手机屏幕大小。只能双指拖拽，并放大寻找文本。比较不方便
建议：增加访问文本的UI支持，添加【复制】按钮，直接复制文本。可以达到“局域网”共享粘贴板一样的能力。

**Comment by songquanpeng** [comment]
感谢反馈，目前初步打算是，针对文本类型，返回 HTML 页面，提供供用户操作的 UI。

**Comment by yuyongID** [comment]
> 

需要做机型适配测试的话，可以跟我说，我这里设备比较多。

**Comment by songquanpeng** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月3日(星期二) 晚上6:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [songquanpeng/go-file] 建议文本访问增加UI，可以适配移动端快速复制文本内容 (Issue #21)





   
需要做机型适配测试的话，可以跟我说，我这里设备比较多。

**Comment by songquanpeng** [comment]
移动端请求以 `.txt` 结尾的文件时将返回以下页面：
![image](https://user-images.githubusercontent.com/39998050/231936878-64c2e67c-bc97-4260-99b7-95a12229e11f.png)

**Comment by songquanpeng** [comment]
新版本今天会 release

**Comment by yuyongID** [comment]
> 新版本今天会 release

新版多个安卓手机和iOS手机访问都可以，功能正常👍🏻
