### ISSUE TITLE
支持修改点击标题后的默认行为

### ISSUE THREAD

**Issue by yuyongID** [songquanpeng/go-file#22]
场景：当上传了「无意义」大量图片或文件时，无法确定需要下载的是哪一个。
建议：将点击名字的默认动作，从「下载」改为『预览』

**Comment by songquanpeng** [comment]
实际上这个就是预览按钮：
![image](https://user-images.githubusercontent.com/39998050/211276162-2c72a320-912b-406e-986d-5fcc5cffca13.png)

目前是通过在另一个页面打开文件的方式来进行文件预览，不过当前正在重构前后端，该功能会得到改进。

感谢反馈~

**Comment by yuyongID** [comment]
> 

感觉点击名字是预览操作，比较服务常规印象。

**Comment by songquanpeng** [comment]
之后会考虑支持用户个性化配置，来选择默认动作。

**Comment by songquanpeng** [comment]
现在点击标题后将开启一个预览模态框。
