### ISSUE TITLE
对于整个项目的体验与感受？

### ISSUE THREAD

**Issue by baiyishaoxia** [songquanpeng/go-file#24]
这里你是不是写错啦？我看初始化表的时候都是不带 `s` 的？
![image](https://user-images.githubusercontent.com/34636159/223331833-ff20e47a-ecfb-4a6a-8ff3-0602229df703.png)

**Comment by songquanpeng** [comment]
Gorm 会自动加 `s`：
![image](https://user-images.githubusercontent.com/39998050/223334679-1ca7bf82-ed1a-4dae-a62a-37202aad4adc.png)

**Comment by baiyishaoxia** [comment]
> 
我更改了一些方向：
1. 去除了由 os 标准库 `GetEnv` 读取配置，改为yml加载。。
2. 去除了`github.com/jinzhu/gorm`封装的驱动，改为官方驱动
3. 我上午跑了一下，更改了许多内容，有必要提一下pull分支给你看看吗?
![image](https://user-images.githubusercontent.com/34636159/223342330-2a8278f2-37b8-45f3-9bbb-58b1a2200f85.png)

**Comment by songquanpeng** [comment]
1. yml 加载这个可以有，但是没有必要去掉之前的环境变量方式，因为要考虑到兼容之前版本，并且有时候部署到某些平台上时只能通过环境变量的方式进行加载。
2. 这个官方驱动有什么好处吗？
3. 实际上我在重构这个项目，`dev` 分支可以看到，前后端基本上重写了，只是因为最近比较忙，所以暂时搁置了。

**Comment by songquanpeng** [comment]
1. 启动的话可以考虑使用[启动器](https://github.com/songquanpeng/gofile-launcher)或者 Docker 启动。
2. 这个为了保持兼容性不方便改。
3. 是这样的，当前基于 gotemplate 的模板渲染方法不方便加复杂的功能。
