### ISSUE TITLE
支持 PicGo

### ISSUE THREAD

**Issue by wisonlau** [songquanpeng/go-file#29]
1.希望能支持picgo
2.我传了2个文件,1个图床文件;首页只能看到文件,看不到图床图片,去图床栏目下也无法看到图片

图床可以参考https://github.com/icret/EasyImages2.0 ,感觉他的图床页面做得不错,我目前用这个,但是漏洞贼多导致我不敢开放外网.

**Comment by songquanpeng** [comment]
1. 我看了一下，貌似是需要开发一个插件，应该不会太麻烦。
2. 图床文件是不在首页显示的，相关的管理功能还没就绪。

**Comment by songquanpeng** [comment]
插件已可用：https://github.com/songquanpeng/picgo-plugin-gofile
