### ISSUE TITLE
I got a error!

### ISSUE THREAD

**Issue by JohyC** [songquanpeng/go-file#4]
wsl run go-file 报错！
`/mnt/d/private/go-file/go-file.exe -port 80 -token private -path /mnt/d/Share`
`
2021/12/09 11:15:47 [Recovery] 2021/12/09 - 11:15:47 panic recovered:
runtime error: invalid memory address or nil pointer dereference
C:/Program Files/Go/src/runtime/panic.go:212 (0xa3f104)
C:/Program Files/Go/src/runtime/signal_windows.go:239 (0xa3efbe)
C:/Users/song/Documents/Projects/Go/go-file/controller.go:44 (0xf36dbb)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xea36e1)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/recovery.go:99 (0xea36c7)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xea27c6)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/logger.go:241 (0xea2785)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xe98e6f)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 (0xe98e55)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 (0xe98944)
C:/Program Files/Go/src/net/http/server.go:2887 (0xcb4f89)
C:/Program Files/Go/src/net/http/server.go:1952 (0xcb030c)
C:/Program Files/Go/src/runtime/asm_amd64.s:1371 (0xa5ef20)
`
不能访问自定义的共享文件夹

**Comment by songquanpeng** [comment]
我刚刚在 [Gitpod](https://gitpod.io/#https://github.com/songquanpeng/go-file) 里提供的 Linux 环境下试了一下，是 Okay 的：
![image](https://user-images.githubusercontent.com/39998050/145398316-23078eba-b4a7-4481-aa54-9433195ccccb.png)

**Comment by songquanpeng** [comment]
看错了，原来你是运行的是 Windows 下的可执行程序，我刚刚试了一下，如果填的 path 是非法的话确实会报错：
```
PS C:\Users\me> go-file.exe -path /sadf
[GIN] 2021/12/09 - 20:45:37 | 200 |      2.6853ms |             ::1 | GET      "/"
[GIN] 2021/12/09 - 20:45:37 | 200 |     64.0442ms |             ::1 | GET      "/public/static/app.css"
[GIN] 2021/12/09 - 20:45:37 | 200 |      35.184ms |             ::1 | GET      "/public/static/main.js"
[GIN] 2021/12/09 - 20:45:37 | 200 |      35.184ms |             ::1 | GET      "/public/lib/qrious.min.js"
[GIN] 2021/12/09 - 20:45:37 | 200 |     64.8532ms |             ::1 | GET      "/public/lib/bulma.min.css"
[GIN] 2021/12/09 - 20:45:37 | 200 |       227.3µs |             ::1 | GET      "/public/lib/qrious.min.js"
[GIN] 2021/12/09 - 20:45:37 | 200 |            0s |             ::1 | GET      "/public/static/main.js"
[GIN] 2021/12/09 - 20:45:38 | 404 |            0s |             ::1 | GET      "/favicon.ico"


2021/12/09 20:45:39 [Recovery] 2021/12/09 - 20:45:39 panic recovered:
runtime error: invalid memory address or nil pointer dereference
C:/Program Files/Go/src/runtime/panic.go:212 (0x69f104)
C:/Program Files/Go/src/runtime/signal_windows.go:239 (0x69efbe)
C:/Users/song/Documents/Projects/Go/go-file/controller.go:44 (0xb96dbb)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xb036e1)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/recovery.go:99 (0xb036c7)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xb027c6)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/logger.go:241 (0xb02785)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xaf8e6f)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 (0xaf8e55)
C:/Users/song/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 (0xaf8944)
C:/Program Files/Go/src/net/http/server.go:2887 (0x914f89)
C:/Program Files/Go/src/net/http/server.go:1952 (0x91030c)
C:/Program Files/Go/src/runtime/asm_amd64.s:1371 (0x6bef20)

[GIN] 2021/12/09 - 20:45:39 | 500 |      2.3611ms |             ::1 | GET      "/explorer"
[GIN] 2021/12/09 - 20:45:39 | 200 |       616.3µs |             ::1 | GET      "/public/lib/bulma.min.css"
[GIN] 2021/12/09 - 20:45:39 | 200 |       616.3µs |             ::1 | GET      "/public/static/app.css"
[GIN] 2021/12/09 - 20:45:39 | 200 |            0s |             ::1 | GET      "/public/lib/qrious.min.js"
[GIN] 2021/12/09 - 20:45:39 | 200 |            0s |             ::1 | GET      "/public/static/main.js"
```
这种在 WSL 环境下调用 Windows 程序并使用挂载的 Windows 目录的情况我确实没想到 hhh，建议使用 `D:\Share` 试一下。

**Comment by JohyC** [comment]
> 看错了，原来你是运行的是 Windows 下的可执行程序，我刚刚试了一下，如果填的 path 是非法的话确实会报错：
> 
> ```
> PS C:\Users\me> go-file.exe -path /sadf
> [GIN] 2021/12/09 - 20:45:37 | 200 |      2.6853ms |             ::1 | GET      "/"
> [GIN] 2021/12/09 - 20:45:37 | 200 |     64.0442ms |             ::1 | GET      "/public/static/app.css"
> [GIN] 2021/12/09 - 20:45:37 | 200 |      35.184ms |             ::1 | GET      "/public/static/main.js"
> [GIN] 2021/12/09 - 20:45:37 | 200 |      35.184ms |             ::1 | GET      "/public/lib/qrious.min.js"
> [GIN] 2021/12/09 - 20:45:37 | 200 |     64.8532ms |             ::1 | GET      "/public/lib/bulma.min.css"
> [GIN] 2021/12/09 - 20:45:37 | 200 |       227.3µs |             ::1 | GET      "/public/lib/qrious.min.js"
> [GIN] 2021/12/09 - 20:45:37 | 200 |            0s |             ::1 | GET      "/public/static/main.js"
> [GIN] 2021/12/09 - 20:45:38 | 404 |            0s |             ::1 | GET      "/favicon.ico"
> 
> 
> 2021/12/09 20:45:39 [Recovery] 2021/12/09 - 20:45:39 panic recovered:
> runtime error: invalid memory address or nil pointer dereference
> C:/Program Files/Go/src/runtime/panic.go:212 (0x69f104)
> C:/Program Files/Go/src/runtime/signal_windows.go:239 (0x69efbe)
> C:/Users/me/Documents/Projects/Go/go-file/controller.go:44 (0xb96dbb)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xb036e1)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/recovery.go:99 (0xb036c7)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xb027c6)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/logger.go:241 (0xb02785)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0xaf8e6f)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 (0xaf8e55)
> C:/Users/me/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 (0xaf8944)
> C:/Program Files/Go/src/net/http/server.go:2887 (0x914f89)
> C:/Program Files/Go/src/net/http/server.go:1952 (0x91030c)
> C:/Program Files/Go/src/runtime/asm_amd64.s:1371 (0x6bef20)
> 
> [GIN] 2021/12/09 - 20:45:39 | 500 |      2.3611ms |             ::1 | GET      "/explorer"
> [GIN] 2021/12/09 - 20:45:39 | 200 |       616.3µs |             ::1 | GET      "/public/lib/bulma.min.css"
> [GIN] 2021/12/09 - 20:45:39 | 200 |       616.3µs |             ::1 | GET      "/public/static/app.css"
> [GIN] 2021/12/09 - 20:45:39 | 200 |            0s |             ::1 | GET      "/public/lib/qrious.min.js"
> [GIN] 2021/12/09 - 20:45:39 | 200 |            0s |             ::1 | GET      "/public/static/main.js"
> ```
> 
> 这种在 WSL 环境下调用 Windows 程序并使用挂载的 Windows 目录的情况我确实没想到 hhh，建议试一下 path 使用 `D:\share` 或者使用 Linux 版本的程序。

我想的是在公司局域网里面放个go-file，同事之间传文件会方便很多。不需要经过钉钉微信啥的。
path 用 `D:\share`  我也试过了，都会报同样的错。。。
除了自定义目录外，其他功能都非常好用。
期待开发计划的目标实现！（我要会golang我也做点贡献。）
期待新版本！

**Comment by songquanpeng** [comment]
请问 Linux 版本试过了吗？

**Comment by JohyC** [comment]
> 请问 Linux 版本试过了吗？

还没有时间试，这两天加班挺烦。。。

**Comment by JohyC** [comment]
> 请问 Linux 版本试过了吗？

Linux版运行失败呀！我得到了这个。 这是什么依赖我没装吗？
![image](https://user-images.githubusercontent.com/38210128/145915512-4484d735-04d8-4f42-9d60-267da9cd19fe.png)

**Comment by songquanpeng** [comment]
没有运行失败，这个是用来在 Linux 系统下打开浏览器用的。

**Comment by JohyC** [comment]
> 没有运行失败，这个是用来在 Linux 系统下打开浏览器用的。

wsl2下运行Linux版体验了一下，遇到了点问题；
由于wsl2和Windows网卡不互通，wsl2下运行Linux版go-file会导致别的机器不能访问。只能本机访问，除非nginx反代出去。。。
我现在是自己写了个 vbs使用exe文件实现开机自启，局域网分享。
除了不能自定义文件夹外其他都是没毛病的！
[go-file.zip](https://github.com/songquanpeng/go-file/files/7710098/go-file.zip)

**Comment by songquanpeng** [comment]
要不试一下在 PowerShell 里启动应用？不要在 WSL 里启动 exe 文件，我感觉 WSL 下 Windows 目录的访问是个坑。

**Comment by JohyC** [comment]
> 要不试一下在 PowerShell 里启动应用？不要在 WSL 里启动 exe 文件，我感觉 WSL 下 Windows 目录的访问是个坑。

明天摸鱼的时候琢磨一下，powershell我还不是很熟悉。

**Comment by JohyC** [comment]
> 要不试一下在 PowerShell 里启动应用？不要在 WSL 里启动 exe 文件，我感觉 WSL 下 Windows 目录的访问是个坑。

可以的！powershell很强大，调用也很简单！

`vbs
set ws=CreateObject("WScript.Shell")
ws.Run "D:\private\go-file\go-file.bat",0,false
`
`powershell
D:\private\go-file\go-file.exe -port 80 -token private -path D:\Share
`

**Comment by songquanpeng** [comment]
嗯嗯，那就先关 issue 了，有问题再开 : )
