### ISSUE TITLE
作者大大您好，请教一下如何加Path参数？

### ISSUE THREAD

**Issue by ransekuang** [songquanpeng/go-file#5]
作者大大您好，我在网上无意间发现您制作的这个软件，感觉非常好用，但是在共享文件夹时遇到了问题。
“如果需要分享文件夹，加 path 参数：./go-file.exe -path ./this/is/a/path”
请问这个加path参数是在哪添加的，在百度上我没有搜索到相关答案，所以在这里提交疑问，希望能得到您的答复，感谢🤝

**Comment by songquanpeng** [comment]
比如说你想分享 `F:\Courses` 这个文件夹下的文件：
命令为：`go-file.exe -path F:\Courses`
![image](https://user-images.githubusercontent.com/39998050/148689367-30a566dc-89da-441f-907a-89b9087bad0b.png)

![image](https://user-images.githubusercontent.com/39998050/148689414-456ce439-aab7-4945-8b18-5f693dff53d7.png)

**Comment by songquanpeng** [comment]
点击导航栏上的 Explorer 即可找到文件列表。

**Comment by songquanpeng** [comment]
我知道了吗，你应该是不知道怎么在终端打开软件，我说下另一种方式：
1. 首先给 go-file.exe 创建一个快捷方式：
![image](https://user-images.githubusercontent.com/39998050/148689574-617cf233-c444-4517-aebc-8c250f68e70d.png)
2. 之后对快捷方式右键，选择属性。
3. 之后在 target 栏里填 `F:\Bin\go-file.exe -path  ./this/is/a/path`，注意这里的 exe 的路径要填你的电脑上的路径（应该也不用你填，里面应该已经有了），不能直接用我这里的值：
![image](https://user-images.githubusercontent.com/39998050/148689660-f5d66880-703c-4708-a0a7-6a0f940f89e6.png)
4. 之后直接双击这个快捷方式即可。

**Comment by ransekuang** [comment]
非常感谢，已经可以了！！！

**Comment by songquanpeng** [comment]
现在新做了一个启动器，不需要命令行操作了：https://github.com/songquanpeng/gofile-launcher
