### ISSUE TITLE
请问是否支持 macOS？

### ISSUE THREAD

**Issue by tasdf** [songquanpeng/go-file#6]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/31894367/167794530-3034b923-0035-4342-917e-8e41f1e6b882.png">

**Comment by songquanpeng** [comment]
应用本身是跨平台的，但是我手头没有 macOS 设备，没办法调试。

根据你提供的信息，简单搜了一下，看下这个：
https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus
