### ISSUE TITLE
部分使用问题优化

### ISSUE THREAD

**Issue by Jonnyan404** [songquanpeng/go-file#8]
1. 无权限上传/管理文件的用户,应当隐藏相关操作按钮,这样更直观
2. 建议使用github-actions自动打包多平台二进制包

**Comment by songquanpeng** [comment]
1. 第一个之前想做，但是 gotemplate 太难用了，之后会加上的。
2. 好建议谢谢！

**Comment by kingname** [comment]
试一试用 gin-vue-admin重构一下。别用gotemplate.
