### ISSUE TITLE
请问一下mac怎么使用呢？没有看懂文档

### ISSUE THREAD

**Issue by xiaoge404** [songquanpeng/go-file#9]
请问一下mac怎么使用呢？没有看懂文档

**Comment by xiaoge404** [comment]
可以出一个教程吗

**Comment by songquanpeng** [comment]
1. 下载文件到某个路径。
2. 在该路径打开终端。
3. 使其可执行：`chmod u+x go-file-macos`

注意你要下载 macOS 版本的文件：https://github.com/songquanpeng/go-file/releases/download/v0.4.1/go-file-macos

因为我手头没有 Mac，就没办法截图展示了。

**Comment by 80imike** [comment]
> 
mac 版本用不了，报这个错 zsh: exec format error: ./go-file-macos

**Comment by songquanpeng** [comment]
尴尬，是我写错了，https://github.com/songquanpeng/go-file/blob/90d247cf8716fe51866767d15851871f9099e107/.github/workflows/macos-release.yml#L9

打包成 Linux 的可执行文件了。

**Comment by songquanpeng** [comment]
M1 版本：
[go-file.zip](https://github.com/songquanpeng/go-file/files/9091248/go-file.zip)

**Comment by 80imike** [comment]
> 

mac  inter 版本来一个

**Comment by 80imike** [comment]
> 上面那个是让同学帮忙编译的，amd64 版本没机器搞不成。
> 
> 等下次 release 让 GitHub Action 自动打包了，或者自行编译：
> 
> ```shell
> git clone https://github.com/songquanpeng/go-file/
> cd go-file
> go env -w GOPROXY=https://goproxy.cn,direct
> go build -ldflags "-s -w -extldflags '-static'" -o go-file
> ```

好的 我等下次打包 一般多久打一次包？

**Comment by songquanpeng** [comment]
v0.4.2 版本打包了 macOS 的 x86 版本，详见：https://github.com/songquanpeng/go-file/releases/tag/v0.4.2
